import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import MyProfilePic from "./components/MyProfilePic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kennedy's Blog",
  description: "Generated by Kennedy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800 min-h-screen">
        <Navbar />
        <MyProfilePic/>
        {children}
      </body>
    </html>
  );
}
